baseURL = "https://xibolun.github.io" # <head> 里面的 baseurl 信息，填你的博客地址
title = "Peng ganyu blog" # 浏览器的标题
languageCode = "zh-cn" # 语言
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
theme = "mogege" # 主题 (需要自己下载)


paginate = 20 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt


preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
  posts = "/:year/:filename/"

[menu]

  [[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 10

  [[menu.main]]
    name = "Tools"
    url = "/tags/tool/"
    weight = 20

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 40

  [[menu.main]]
    name = "读书"
    url = "/books"
    weight = 42


  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 50

[params]
    since = 2017
    author = "pengganyu"                          # Author's name
    avatar = "/img/person/face.png"           # Author's avatar
    subtitle = "Just for Fun"                  # Subtitle
    home_mode = "" # post or other
    enableUtterances = true  # Utterances 评论系统

    google_verification = ""

    description = "Peng ganyu的个人博客" # (Meta) 描述

    beian = ""
    googleAnalytics = "UA-101106729-1" # Google 统计 id

    busuanzi = true # 不蒜子计数
    # license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.utteranc] # Homepage: https://utteranc.es
    repo = "xibolun/xibolun.github.io" # The repo to store comments
    issueTerm = "pathname" # the mapping between blog posts and GitHub issues. 
    theme = "github-light" # Theme
    crossorigin = "anonymous" # default: anonymous